-   id: isort
    name: isort
    stages: [commit]
    language: conda
    additional_dependencies: ['isort']
    args: [ "--profile", "black",--line-length=120 ]
    entry: isort
    types: [python]
    always_run: false

-   id: black
    name: black
    stages: [commit]
    language: conda
    additional_dependencies: ['black']
    entry: black
    args: [ --line-length=120 ]
    types: [python]
    always_run: true

-   id: flake8
    name: flake8
    stages: [commit]
    language: conda
    additional_dependencies: ['flake8']
    entry: flake8
    types: [python]
    exclude: setup.py
    always_run: true

-   id: mypy
    name: mypy
    stages: [commit]
    language: conda
    additional_dependencies: ['mypy']
    entry: tools/types/mypy_wrapper.sh
    types: [python]
    require_serial: true
    always_run: true

-   id: pytest
    name: pytest
    stages: [commit]
    language: conda
    additional_dependencies: ['pytest']
    entry: tools/test/pytest_wrapper.sh
    types: [python]
    pass_filenames: false
    always_run: true

-   id: pytest-cov
    name: pytest
    stages: [push]
    language: conda
    additional_dependencies: ['pytest']
    entry: pytest --cov --cov-fail-under=40
    types: [python]
    pass_filenames: false
    always_run: true
