-   id: pre-commit-autoupdater
    name: pre-commit-autoupdater
    entry: pre-commit autoupdate
    language: script
    description: Updates the version of the repositorties to the latest tag available for them
    always_run: true
    stages: [commit]

-   id: isort
    name: isort
    stages: [commit]
    language: conda
    args: [ "--profile", "black",--line-length=120 ]
    entry: isort
    types: [python]
    always_run: false

-   id: black
    name: black
    stages: [commit]
    language: conda
    entry: black
    args: [ --line-length=120 ]
    types: [python]
    always_run: true

-   id: flake8
    name: flake8
    stages: [commit]
    language: conda
    entry: flake8
    types: [python]
    exclude: setup.py
    always_run: true

-   id: mypy
    name: mypy
    stages: [commit]
    language: script
    entry: mypy-wrapper/mypy_wrapper.sh
    types: [python]
    require_serial: true
    always_run: true

-   id: pytest
    name: pytest
    stages: [commit]
    language: script
    entry: pytest-wrapper/pytest_wrapper.sh
    types: [python]
    pass_filenames: false
    always_run: true
    #verbose: true

-   id: pytest-cov
    name: pytest-cov
    stages: [push]
    language: conda
    additional_dependencies: ['pytest']
    entry: pytest --cov --cov-fail-under=20
    types: [python]
    pass_filenames: false
    always_run: true

-   id: conventional-pre-commit
    name: Conventional Commit
    entry: conventional-commit/conventional-pre-commit.sh
    language: script
    description: Checks commit message for Conventional Commits formatting
    always_run: true
    stages: [commit-msg]
