repos:
  repo: https://github.com/jareyl/conda-env-precommit-hooks
  rev: 1.0.9
  hooks:
  - id: isort
    additional_dependencies: ['isort']
  - id: black
    additional_dependencies: ['black']
  - id: flake8
    additional_dependencies: ['flake8']
  - id: mypy
    additional_dependencies: ['mypy']
  - id: pytest
    additional_dependencies: ['pytest']
  - id: pytest-cov
    additional_dependencies: ['pytest']

